### ISSUE TITLE
Workaround

### ISSUE THREAD

**Issue by buddydvd** [scottcarter/VideoCompositionSimulatorBug#1]
I stumbled onto the same problem and discovered a workaround.

I changed my code from this

```
[AVAssetReaderVideoCompositionOutput
 assetReaderVideoCompositionOutputWithVideoTracks:videoTracks
 videoSettings:nil]
```

to this

```
[AVAssetReaderVideoCompositionOutput
 assetReaderVideoCompositionOutputWithVideoTracks:[videoTracks arrayByAddingObjectsFromArray:videoTracks]
 videoSettings:nil]
```

If an asset has two tracks—say an audio track and a video track— and the video track has a trackID of 2, the simulator works fine. On other hand, if the video track's trackID is 1, the simulator hangs at `copyNextSampleBuffer`. Duplicating the video tracks we pass to AVAssetReaderVideoCompositionOutput appears to work around this issue. Not sure why, but hope it helps.

**Comment by scottcarter** [comment]
Thanks for the workaround!  I just verified that it works.  I'll add a note to the README.md file.
